# Generated by Django 5.0.7 on 2024-07-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_question_model_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
