# Generated by Django 5.0.7 on 2024-07-17 16:58

from django.db import migrations

def create_initial_data(apps, schema_editor):
    Quiz = apps.get_model('quiz_app', 'Quiz')
    Question = apps.get_model('quiz_app', 'Question')

    # Create a quiz
    quiz = Quiz.objects.create(title="Sample Quiz", description="This is a sample quiz.")

    # Create questions
    question_answers = [
        ("What is the capital of France?", "Paris"),
        ("What is the largest planet in our solar system?", "Jupiter"),
        ("Who wrote 'To Kill a Mockingbird'?", "Harper Lee"),
        ("What is the smallest prime number?", "2"),
        ("What year did the Titanic sink?", "1912")
    ]

    for (question_text, answer) in question_answers:
        q = Question.objects.create(question_text=question_text, model_answer=answer)
        quiz.questions.add(q)

class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_rename_question_question_question_text_delete_answer'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
