# Generated by Django 5.0.7 on 2024-07-17 18:22

from django.db import migrations

def create_initial_responses(apps, schema_editor):
    Quiz = apps.get_model('quiz_app', 'Quiz')
    Response = apps.get_model('quiz_app', 'QuizResponse')

    # Get all existing quizzes
    quizzes = Quiz.objects.all()

    # Create an empty response for each quiz
    for quiz in quizzes:
        Response.objects.create(quiz=quiz)

class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_remove_questionresponse_quiz_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_responses),
    ]
